### ISSUE TITLE
Neovide on Flathub

### ISSUE THREAD

**Issue by sqwxl** [neovide/neovide#2412]
## Goal

Neovide currently has a snap package, but no Flathub package. As a Fedora Silverblue user, I'd love to be able to `flatpak install neovide` and I'm sure a lot of other flatpak users would like to see this.

## Work in progress

I've already made a working flatpak package of Neovide: https://github.com/sqwxl/flathub/tree/dev.neovide.neovide (to try it out you can clone that repo and run `flatpak run org.flatpak.Builder --user --install --install-deps-from=flathub --ccache build dev.neovide.neovide.yml`) 

I've opened a PR to the Flathub repo (https://github.com/flathub/flathub/pull/5017), but there are still a number of changes to make before it is approved.

Because of the sandboxing inherent to flatpaks, it was necessary to introduce an upstream change to Neovide allowing the container access to outside binaries. See my PR here: https://github.com/neovide/neovide/pull/2397

## To-Do

As a way to track progress towards the goal of getting Neovide published here are the tasks to be completed as far as I can tell:

- [ ] https://github.com/neovide/neovide/pull/2397
- [x] Add access to clipboard provider from within flatpak container
- [ ] https://github.com/flathub/flathub/pull/5017
  - [ ] #2413 
  - [x] https://github.com/flathub-infra/flatpak-builder-lint/pull/336
- [ ] Automate flatpak update on release

**Comment by gmankab** [comment]
published to flathub - https://flathub.org/apps/dev.neovide.neovide

**Comment by sqwxl** [comment]
Awesome! Thank you!
